//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaelstrom.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GAME_RESOLUTION {
            get {
                return ((string)(this["GAME_RESOLUTION"]));
            }
            set {
                this["GAME_RESOLUTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OCR_SPACE_APIKEY {
            get {
                return ((string)(this["OCR_SPACE_APIKEY"]));
            }
            set {
                this["OCR_SPACE_APIKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wizard101")]
        public string THEME_MODE {
            get {
                return ((string)(this["THEME_MODE"]));
            }
            set {
                this["THEME_MODE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SPEED_MULTIPLIER {
            get {
                return ((double)(this["SPEED_MULTIPLIER"]));
            }
            set {
                this["SPEED_MULTIPLIER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ENABLE_SCREEN_CAPTURE {
            get {
                return ((bool)(this["ENABLE_SCREEN_CAPTURE"]));
            }
            set {
                this["ENABLE_SCREEN_CAPTURE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENABLE_AUDIO_RECOGNIZER {
            get {
                return ((bool)(this["ENABLE_AUDIO_RECOGNIZER"]));
            }
            set {
                this["ENABLE_AUDIO_RECOGNIZER"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ENABLE_SELF_TUNING {
            get {
                return ((bool)(this["ENABLE_SELF_TUNING"]));
            }
            set {
                this["ENABLE_SELF_TUNING"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.12")]
        public double AUDIO_TRANSIENT_DELTA {
            get {
                return ((double)(this["AUDIO_TRANSIENT_DELTA"]));
            }
            set {
                this["AUDIO_TRANSIENT_DELTA"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UPDATE_FEED_URL {
            get {
                return ((string)(this["UPDATE_FEED_URL"]));
            }
            set {
                this["UPDATE_FEED_URL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_CHECK_UPDATES {
            get {
                return ((bool)(this["AUTO_CHECK_UPDATES"]));
            }
            set {
                this["AUTO_CHECK_UPDATES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_PAUSE_ON_FOCUS_LOSS {
            get {
                return ((bool)(this["AUTO_PAUSE_ON_FOCUS_LOSS"]));
            }
            set {
                this["AUTO_PAUSE_ON_FOCUS_LOSS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mixed")]
        public string LEARN_MODE_PROFILE {
            get {
                return ((string)(this["LEARN_MODE_PROFILE"]));
            }
            set {
                this["LEARN_MODE_PROFILE"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int BAZAAR_GOLD_MIN {
            get {
                return ((int)(this["BAZAAR_GOLD_MIN"]));
            }
            set {
                this["BAZAAR_GOLD_MIN"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380000")]
        public int BAZAAR_GOLD_CAP {
            get {
                return ((int)(this["BAZAAR_GOLD_CAP"]));
            }
            set {
                this["BAZAAR_GOLD_CAP"] = value;
            }
        }

        public bool ENABLE_DEV_TELEMETRY {
            get {
                return ((bool)(this["ENABLE_DEV_TELEMETRY"]));
            }
            set {
                this["ENABLE_DEV_TELEMETRY"] = value;
            }
        }
        
        public bool ENABLE_DEV_UI_SNAPSHOTS {
            get {
                return ((bool)(this["ENABLE_DEV_UI_SNAPSHOTS"]));
            }
            set {
                this["ENABLE_DEV_UI_SNAPSHOTS"] = value;
            }
        }

        public bool PLAYER_PREVIEW_MODE {
            get {
                return ((bool)(this["PLAYER_PREVIEW_MODE"]));
            }
            set {
                this["PLAYER_PREVIEW_MODE"] = value;
            }
        }
    }
}
